#!/usr/bin/env php
<?php

use SPSOstrov\Runtime\Run;

require_once getenv("SPSO_APP_AUTOLOAD_PHP");

array_shift($argv);
$terminalMode = array_shift($argv);
$user = array_shift($argv);
if ($user === '') {
    $user = null;
}

if ($terminalMode === "T") {
    $terminalMode = "no-terminal";
} elseif ( "$terminalMode" === "t") {
    $terminalMode = "terminal";
}

if (empty($argv)) {
    fprintf(STDERR, "Error: No container or environment was specified\n");
    exit(1);
}

$container = array_shift($argv);

$cmd = ["compose", "exec"];
if ($terminalMode === "auto" || $terminalMode === "no-terminal") {
    if ($terminalMode !== 'no-terminal' && !posix_isatty(STDIN)) {
        $cmd[] = "-T";
    }
}

if ($user !== null) {
    $cmd[] = '--user';
    $cmd[] = $user;
}

$cmd[] = "--";

$cmd[] = $container;

if (empty($argv)) {
    $argv[] = 'bash';
}

exit(Run::app(array_merge($cmd, $argv)));
